# Generated by Django 4.1.4 on 2022-12-17 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2494ae89-277e-41d2-a86d-5ea36781baa2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d59edecc-7dd5-4e17-8b7b-f6977915c5b6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
