# Generated by Django 4.1.4 on 2022-12-17 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0002_alter_blog_id_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b70b0e6-4be4-4d07-9d81-80589e9a8e0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5f78010-eb6a-4581-bcfd-740471500496'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
