# Generated by Django 4.1.4 on 2022-12-17 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0003_blog_created_news_created_alter_blog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('target_link', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.UUID('76bd9b69-fb4f-4015-9b86-444260d39556'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0348a0f1-48bd-4f65-bf94-1ef15959fa5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
