# Generated by Django 4.1.4 on 2022-12-17 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0004_blogs_delete_blog_alter_news_options_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fc1dfb1-8c36-4aa8-a47d-e420a4e64e04'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('681f5a04-b796-41da-9d45-b99d0657bb04'), editable=False, primary_key=True, serialize=False),
        ),
    ]
