# Generated by Django 4.1.4 on 2022-12-17 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0005_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20693673-196f-450c-ae65-e1044f7c30df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d83d1d7-5dde-4229-b12e-417d2e2b5fc3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
