# Generated by Django 4.1.4 on 2022-12-17 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0006_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a0ef355-2247-43c6-9529-c214a0434fe9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e83f5465-9e62-408a-92ff-1bf56b75674a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
