# Generated by Django 4.1.4 on 2023-01-03 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0007_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a327462-607b-4c5a-b74f-6e5c27868a32'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05c91e95-8923-4dfa-91f8-0988d4c01f9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
