# Generated by Django 4.1.4 on 2023-01-03 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0008_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59978759-6a6a-46a7-9b24-17fdfc87c254'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73c5ea52-eff7-41dd-b8f7-e7fa86ef2dd8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
