# Generated by Django 4.1.4 on 2023-01-04 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0010_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53175359-5489-485a-8dd0-66c4b3d7ce5d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d242e9f0-d2ea-4fdc-94bc-c237f9736689'), editable=False, primary_key=True, serialize=False),
        ),
    ]
