# Generated by Django 4.1.4 on 2023-01-04 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0011_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31ef202e-d57e-4edb-9024-6a4f0cc08498'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4daae8d5-378e-4110-bd48-8551654ef5f7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
