# Generated by Django 4.1.4 on 2023-01-04 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0012_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20e998f0-580f-4e2b-983e-19e270918345'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0186ab06-9492-471c-8f65-298357bcda51'), editable=False, primary_key=True, serialize=False),
        ),
    ]
