# Generated by Django 4.1.4 on 2023-01-04 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0013_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('337f6ad2-a842-4e71-ba45-8bc03ee13430'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68b54e03-59d3-4a26-91ff-59a96b58e30e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
