# Generated by Django 4.1.4 on 2023-01-04 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0014_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3aa1fbed-6be2-4bdd-975a-08478578b8f5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17dee709-01f8-4695-bbd4-7ec5bbf5e536'), editable=False, primary_key=True, serialize=False),
        ),
    ]
