# Generated by Django 4.1.4 on 2023-01-04 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0015_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa96ebda-c42d-4794-b3c7-a58b6f7a9200'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b04b2122-67db-446d-acce-b9bfd210feba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
