# Generated by Django 4.1.4 on 2023-01-04 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0016_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b5679df-0d20-4948-bfca-74a1812f61d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a12a2d2e-f3d9-4052-b518-8b0efe22c644'), editable=False, primary_key=True, serialize=False),
        ),
    ]
