# Generated by Django 4.1.4 on 2023-01-04 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0017_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20227dbf-0b94-413a-a1b7-6293cc6a7ccd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebd7602c-e31c-422f-bc71-ea1aca28712d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
