# Generated by Django 4.1.4 on 2023-01-04 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0018_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3d07eb7-9ccd-4a81-982a-351382010b17'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a97bd751-2058-4151-831f-a50b303ea64c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
