# Generated by Django 4.1.4 on 2023-01-04 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0019_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('70cf1165-c914-49de-8d8f-7d85de3e0625'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47d9909f-e4bd-46a5-acc6-2fdfc1d98a4f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
