# Generated by Django 4.1.4 on 2023-01-04 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0020_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44d4e252-4c57-477a-a384-1da48b749759'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88163283-1e9d-4c1e-ad85-ad39813d04a5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
