# Generated by Django 4.1.4 on 2023-01-05 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0021_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('474505e5-3a54-4333-818f-80841bff2b4b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41845d6d-5130-4f9b-b680-3bb7402fa2e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
