# Generated by Django 4.1.4 on 2023-01-05 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0023_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('748c2e4f-37be-477a-b522-44532d0ca3ac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e757b5c-6f85-445b-a3f2-68ec676ab0ab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
