# Generated by Django 4.1.4 on 2023-01-05 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0024_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a519fcec-c53e-4f26-8226-d7e6f68b6d9b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('144b739c-5dde-44a3-bf45-8aff529656dd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
