# Generated by Django 4.1.4 on 2023-01-05 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0025_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34e3be6a-2dca-4c1e-87f2-d2e45a910efc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30062683-6423-414a-b213-6c85488f3598'), editable=False, primary_key=True, serialize=False),
        ),
    ]
