# Generated by Django 4.1.4 on 2023-01-05 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0026_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4beb99a6-d9d2-431f-8c4b-7467674726fb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0900ed48-3219-48ee-958d-247566a3e177'), editable=False, primary_key=True, serialize=False),
        ),
    ]
