# Generated by Django 3.2.16 on 2023-01-11 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0027_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('294439a1-ef71-47df-b1df-a77bc6994729'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('151b70cc-7d1a-414e-afd5-bc803ffa9b31'), editable=False, primary_key=True, serialize=False),
        ),
    ]
