# Generated by Django 4.1.4 on 2023-01-18 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0028_auto_20230111_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9cccfe9-9266-49de-b163-cf7382b68b87'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('700b04e1-c112-4da2-8d73-59c63bdcfe36'), editable=False, primary_key=True, serialize=False),
        ),
    ]
