# Generated by Django 4.1.4 on 2023-01-23 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0029_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80e4c7c8-8b47-46fe-9c3c-a1f51d8e3b55'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5659384b-0056-490c-bb45-23748268a466'), editable=False, primary_key=True, serialize=False),
        ),
    ]
