# Generated by Django 4.1.4 on 2023-01-25 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreads', '0030_alter_blogs_id_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c282642d-bef5-48fd-ba08-637e0833f0cd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('081c8055-09bd-480e-8462-250e15214eac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
