# Generated by Django 4.1.4 on 2022-12-17 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('1', 'causal leave'), ('2', 'sick leave'), ('3', 'emergency leave'), ('4', 'optional holiday')], default='1', max_length=20)),
                ('casual_leave', models.IntegerField(default=12)),
                ('sick_leave', models.IntegerField(default=10)),
                ('emergency_leave', models.IntegerField(default=2)),
                ('optional_holidays', models.IntegerField(default=2)),
                ('date_of_leave', models.DateField()),
                ('no_of_leaves_required', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('leave_notes', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
