# Generated by Django 4.1.4 on 2022-12-17 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(max_length=10)),
                ('checkout', models.CharField(max_length=10)),
                ('hours_perday', models.CharField(max_length=20)),
                ('date_of_checkin', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(upload_to='')),
                ('contact_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('alternate_contact', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')])),
                ('blood_group', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('dob', models.DateField()),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
