# Generated by Django 4.1.4 on 2022-12-17 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_dailyhour_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('422a6944-9542-49c2-a806-05ec440be2f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2072e909-424f-4237-aeac-21cb13e12a6a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a3110c2-1ddd-44be-84d8-f8b7ff4cdf6e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
