# Generated by Django 4.1.4 on 2022-12-17 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_leave_employee_alter_dailyhour_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comp_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ffcffdb-cde5-4444-b256-37a377b1848d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fc2ff55-0d80-46bc-820c-50f9f1413545'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd147c49-a878-452d-b6fb-41f44add8ba7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('1', 'causal leave'), ('2', 'sick leave'), ('3', 'emergency leave'), ('4', 'Comp OFF'), ('4', 'optional holiday')], default='1', max_length=20),
        ),
    ]
