# Generated by Django 4.1.4 on 2022-12-17 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_leave_comp_off_alter_dailyhour_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36412fba-af89-4a1b-aa8d-5f0129957ef1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be919348-9706-4fe4-8aea-b6fc3abc4b38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fd774f3-2d2b-4cb6-b061-1985ae8f3606'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
