# Generated by Django 4.1.4 on 2022-12-17 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_employee_bio_alter_dailyhour_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='date_of_checkin',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('764b7426-144f-43de-b820-16739fac99f2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e30cfc1a-0d2c-4ea2-aec5-3734dab01b15'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a062b70-9b32-4755-a3f3-33820ae56087'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
