# Generated by Django 4.1.4 on 2022-12-17 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_dailyhour_date_of_checkin_alter_dailyhour_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='date_of_checkin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75bdbeee-fc16-476e-9845-e2e4f25532e4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('447d7bb6-c014-41cb-bb2d-c3ff7dace9d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f91a8890-70cc-4471-8b22-6ad7d369c0dc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
