# Generated by Django 4.1.4 on 2022-12-17 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_dailyhour_date_of_checkin_alter_dailyhour_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d40ead27-9b9a-4757-895d-3f1b71833d8e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed3c8d10-d408-4985-93bc-173926482082'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d883654f-aee9-4262-b7c1-84b908012eec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
