# Generated by Django 4.1.4 on 2022-12-17 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('246a92e4-f8a8-4920-9095-6e80e3d25de7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c152f541-8c2a-493b-80a2-9e4b767ffd80'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ec29475-8e42-4ae9-b164-56b784c0a4c9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
