# Generated by Django 4.1.4 on 2022-12-17 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e21039f-136b-4e55-b2ad-7f9aedeed61c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef990ecf-a39e-47a6-b76d-d0fe45c1c34c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eb1d7e7e-a8e8-488a-a5dd-711a684bd543'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
