# Generated by Django 4.1.4 on 2022-12-17 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9f05858-18a5-4c51-a1cd-b81bdee6b5b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0eaef588-5f59-4cc9-b954-ed50d438832e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e192fb5-dd57-4f03-9019-f9501919fb86'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
