# Generated by Django 4.1.4 on 2022-12-17 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f8b6747-7b9e-4bbd-8008-80dcacb3532e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cf9a4ac-40f5-4f88-a26c-2ec7f8e1f8d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93e0540c-20f2-4d5d-b4f1-fa1ca9446557'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
