# Generated by Django 4.1.4 on 2022-12-17 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('662ecfae-056b-4699-b2d9-421259bdddb2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08c357ef-ce68-47f8-9a52-ebdf1b36b557'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b844095-e4d2-4f76-8fc2-2bfb0931efc2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
