# Generated by Django 4.1.4 on 2022-12-17 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac57a322-6199-4364-a951-0b815716d663'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2bef959-c54c-430a-864b-ee5e93210a3f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6edc0857-9ce1-4217-bd9b-abfe54b876b8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
