# Generated by Django 4.1.4 on 2023-01-03 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_dailyhour_id_alter_employee_id_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61684ada-86f4-45a0-ad6b-41620abb30aa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7797151-d4ab-4733-aac5-f1cc00f11751'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
