# Generated by Django 4.1.4 on 2023-01-03 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1edb79a-a5e1-474e-8a07-e7ddc8fc68f8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd790bd9-5d93-40a8-89ad-d710d60d1eb3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
