# Generated by Django 4.1.4 on 2023-01-04 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_dailyhour_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b879178-44f5-427c-8691-ba273f3fa77e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73f9fd6f-7ad7-455f-8cc6-9edcd7ee3505'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
