# Generated by Django 4.1.4 on 2023-01-04 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5005e36c-5303-4fd1-b1d1-173ae82aaec7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('70fdc8ad-82a5-4715-9c99-f681ee8f0ed2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
