# Generated by Django 4.1.4 on 2023-01-04 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='date_of_checkin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a248579-739f-405d-bf07-b373254feef6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9f14b45-724e-4fdc-9140-33ca8688144d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
