# Generated by Django 4.1.4 on 2023-01-04 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_dailyhour_date_of_checkin_alter_dailyhour_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3536d646-ac26-4683-887b-40e4780002ff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b158ec8-203e-4f10-aa00-315ec5a35ce4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
