# Generated by Django 4.1.4 on 2023-01-04 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e5601ce-375d-44e2-8609-d87737ef5d4b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5568265-2818-43ed-87bf-3e8c74c6013b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
