# Generated by Django 4.1.4 on 2023-01-04 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhour',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d060bc8-0a47-431e-8806-2cf6733172c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9209e18-719d-43f5-80b3-5f09b639f2d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
