# Generated by Django 4.1.4 on 2023-01-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_dailyhour_id_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='no_of_leaves_required',
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_of_leave',
            field=models.DateField(blank=True, null=True),
        ),
    ]
