# Generated by Django 4.1.4 on 2023-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_leave_no_of_leaves_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
