# Generated by Django 4.1.4 on 2023-01-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhour',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
