# Generated by Django 4.1.4 on 2023-01-05 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_dailyhour_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='casual_leave',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='comp_off',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='emergency_leave',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='optional_holidays',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='sick_leave',
        ),
        migrations.CreateModel(
            name='RemainingLeaves',
            fields=[
                ('casual_leave', models.IntegerField(default=12)),
                ('sick_leave', models.IntegerField(default=10)),
                ('emergency_leave', models.IntegerField(default=2)),
                ('comp_off', models.IntegerField(default=0)),
                ('optional_holidays', models.IntegerField(default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
    ]
