# Generated by Django 4.1.4 on 2023-01-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_remove_leave_casual_leave_remove_leave_comp_off_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemainingLeaves',
            new_name='RemainingLeave',
        ),
    ]
