# Generated by Django 4.1.4 on 2023-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_rename_remainingleaves_remainingleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
