# Generated by Django 4.1.4 on 2023-01-05 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='no_of_leaves_required',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
