# Generated by Django 4.1.4 on 2023-01-18 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('date_of_holiday', models.DateField()),
                ('event', models.CharField(blank=True, max_length=200, null=True)),
                ('region_applicable', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
